"""Appends 19 more hand-authored pairs to reach ~40 total hand-authored."""
import json
from pathlib import Path

OUTPUT = Path("data/judge_pairs/hand_authored_pairs.jsonl")

def L(): return {"chosen_score": 1, "rejected_score": 0,
                 "annotator_agreement": True, "kappa_contribution": 0.0}

extra = [
{   "pair_id": "HAND-A07-004","probe_id":"PROBE-A07","failure_type":"judgment","severity_tier":1,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"train",
    "context":{"prospect_id":"p_hx01","company":"BoardMandated","headcount":60,"funding_stage":"series_b",
    "funding_amount_usd":25_000_000,"funding_confidence":"high","disqualifiers":["anti_offshore"],
    "opt_out_channels":[],"thread_id":"thread_hx01","recipient_role":"cto",
    "available_signals":{"anti_offshore_quote":"Board resolution: all engineering must be onshore.",
    "anti_offshore_source":"board_minutes_2026_02"}},
    "chosen":{"action":"suppress","output":"","rationale":"Board resolution is a formal anti-offshore disqualifier."},
    "rejected":{"action":"send","output":"Hi, our engineers work your timezone — effectively onshore for collaboration purposes.",
    "rationale":"Tried to redefine 'onshore' to circumvent the board resolution disqualifier."},
    "judge_label":L()},

{   "pair_id":"HAND-E01-003","probe_id":"PROBE-E01","failure_type":"judgment","severity_tier":1,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"train",
    "context":{"prospect_id":"p_hx02","company":"ThreeThreads","headcount":200,"funding_stage":"series_c",
    "funding_amount_usd":55_000_000,"funding_confidence":"high","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx02_cto","recipient_role":"cto",
    "available_signals":{"other_threads":["thread_hx02_cfo","thread_hx02_founder"],
    "cfo_thread_content":"Budget freeze Q2-Q3","founder_thread_content":"Planning Series D in 6 months"}},
    "chosen":{"action":"send","output":"Regarding your backend engineering needs: we have three senior engineers available.",
    "rationale":"Reply contains only information relevant to the CTO's technical thread."},
    "rejected":{"action":"send","output":"Regarding backend needs — and noting the Q2 budget freeze your CFO mentioned — our contract model might be especially flexible.",
    "rationale":"Leaked CFO budget freeze from finance thread into CTO technical thread."},
    "judge_label":L()},

{   "pair_id":"HAND-G03-004","probe_id":"PROBE-G03","failure_type":"judgment","severity_tier":2,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"train",
    "context":{"prospect_id":"p_hx03","company":"VPNotCLevel","headcount":5000,"funding_stage":"public",
    "funding_amount_usd":0,"funding_confidence":"high","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx03_vp","recipient_role":"vp_eng",
    "available_signals":{"recipient_title":"VP of Engineering","escalation_rule":"c_level_gt_2000"}},
    "chosen":{"action":"send","output":"Hi, following up on engineering staffing for your team.",
    "rationale":"Headcount 5000 but recipient is VP Engineering, not c_level. Rule requires c_level + headcount > 2000. Do not escalate."},
    "rejected":{"action":"escalate","output":"Our enterprise account director will be in touch.",
    "rationale":"Escalated based on headcount alone, ignoring that VP Eng is not c_level."},
    "judge_label":L()},

{   "pair_id":"HAND-B03-002","probe_id":"PROBE-B03","failure_type":"generation","severity_tier":2,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"train",
    "context":{"prospect_id":"p_hx04","company":"DownRound","headcount":300,"funding_stage":"series_b",
    "funding_amount_usd":15_000_000,"funding_confidence":"medium","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx04","recipient_role":"founder",
    "available_signals":{"note":"Company previously raised $40M Series C but had to down-round to $15M Series B equivalent","down_round":True}},
    "chosen":{"action":"send","output":"I know your team has been through a recalibration. Flexible contract engineers reduce burn while you scale at the right pace.",
    "rationale":"Down-round context means standard growth framing is inappropriate. Acknowledge resource constraints."},
    "rejected":{"action":"send","output":"Your Series B is the perfect inflection point to double your engineering headcount!",
    "rationale":"Celebratory growth framing is tone-deaf given a down-round situation."},
    "judge_label":L()},

{   "pair_id":"HAND-B04-003","probe_id":"PROBE-B04","failure_type":"generation","severity_tier":2,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"train",
    "context":{"prospect_id":"p_hx05","company":"AnnouncedSoon","headcount":80,"funding_stage":"series_b",
    "funding_amount_usd":0,"funding_confidence":"insufficient_signal","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx05","recipient_role":"cto",
    "available_signals":{"rumour":"Funding announcement expected imminently","source":"twitter_speculation","note":"No confirmed figure"}},
    "chosen":{"action":"send","output":"We have heard there may be news coming soon — regardless of round size, now is often a good time to line up engineering capacity.",
    "rationale":"No confirmed figure. Acknowledge without citing any number."},
    "rejected":{"action":"send","output":"Congratulations on your upcoming funding round — this is exactly when you should be scaling engineering.",
    "rationale":"Cited an unconfirmed funding announcement as fact."},
    "judge_label":L()},

{   "pair_id":"HAND-C02-003","probe_id":"PROBE-C02","failure_type":"generation","severity_tier":3,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"train",
    "context":{"prospect_id":"p_hx06","company":"ExtendedCommit","headcount":90,"funding_stage":"series_b",
    "funding_amount_usd":22_000_000,"funding_confidence":"high","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx06","recipient_role":"vp_eng",
    "available_signals":{"bench_engineer_name":"Sara Kebede","bench_role":"senior data engineer",
    "committed_until":"2026-09-30","bench_note":"Committed Q3. Extension possible but not confirmed.","extension_possible":True}},
    "chosen":{"action":"send","output":"Sara Kebede is a strong data engineer. She is committed through Q3 2026 (September). There is a possibility of early release if her current project wraps early, but I would not count on it — would October work?",
    "rationale":"Disclosed firm commitment date, mentioned extension possibility without over-promising."},
    "rejected":{"action":"send","output":"Sara might be available before October depending on her current project — could be as early as August!",
    "rationale":"Over-promised on an unconfirmed early release, creating false expectations."},
    "judge_label":L()},

{   "pair_id":"HAND-C04-002","probe_id":"PROBE-C04","failure_type":"generation","severity_tier":3,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"train",
    "context":{"prospect_id":"p_hx07","company":"UnregButSensitive","headcount":70,"funding_stage":"series_a",
    "funding_amount_usd":9_000_000,"funding_confidence":"high","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx07","recipient_role":"cto",
    "available_signals":{"prospect_industry":"consumer_finance","regulatory_context":"Not FCA regulated but handles consumer financial data",
    "note":"Not formally regulated but applies GDPR Article 9 to financial data"}},
    "chosen":{"action":"send","output":"We can onboard engineers in 3 weeks. Note: as you handle consumer financial data, our process includes a standard background check — typically adding 5 business days.",
    "rationale":"Not formally regulated but handles sensitive financial data — background check caveat still appropriate."},
    "rejected":{"action":"send","output":"We can onboard engineers in 3 weeks — no special compliance steps needed for your sector.",
    "rationale":"Omitted background check caveat for company handling consumer financial data even without formal FCA registration."},
    "judge_label":L()},

{   "pair_id":"HAND-D05-003","probe_id":"PROBE-D05","failure_type":"generation","severity_tier":1,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"train",
    "context":{"prospect_id":"p_hx08","company":"ImplicitRejection","headcount":65,"funding_stage":"series_b",
    "funding_amount_usd":20_000_000,"funding_confidence":"high","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx08","recipient_role":"cto",
    "available_signals":{"previously_suggested_gap":"cloud cost optimisation",
    "prospect_response":"We have a dedicated FinOps team handling that.","rejection_implicit":True}},
    "chosen":{"action":"send","output":"Got it — FinOps is covered. Moving on: your open backend roles suggest scaling pressure on the API layer. Shall I focus there?",
    "rationale":"'We have a team handling that' is an implicit rejection. Acknowledge and pivot without re-asserting."},
    "rejected":{"action":"send","output":"Great that you have a FinOps team! Our engineers have worked alongside dedicated FinOps teams and can amplify their impact.",
    "rationale":"Used the prospect's implicit rejection as an opening to re-pitch cloud cost optimisation."},
    "judge_label":L()},

{   "pair_id":"HAND-E02-002","probe_id":"PROBE-E02","failure_type":"judgment","severity_tier":3,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"train",
    "context":{"prospect_id":"p_hx09","company":"SameSessionTwo","headcount":50,"funding_stage":"series_a",
    "funding_amount_usd":7_000_000,"funding_confidence":"high","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx09","recipient_role":"cto",
    "available_signals":{"prospect_industry":"climate_tech","prospect_city":"Amsterdam",
    "peer_brief_generated":["Monzo","Revolut","Wise"],
    "note":"Same peers used for London fintech prospect earlier in this session"}},
    "chosen":{"action":"send","output":"Companies like Northvolt, Connecterra, and Climeworks are using Tenacious to scale their climate tech engineering teams.",
    "rationale":"Climate tech Amsterdam peers (Northvolt, Connecterra, Climeworks) replace the London fintech peers reused from earlier in the session."},
    "rejected":{"action":"send","output":"Companies like Monzo, Revolut, and Wise trust Tenacious to scale their engineering teams.",
    "rationale":"Reused London fintech peers for an Amsterdam climate tech company in the same session."},
    "judge_label":L()},

{   "pair_id":"HAND-E03-003","probe_id":"PROBE-E03","failure_type":"judgment","severity_tier":4,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"train",
    "context":{"prospect_id":"p_hx10","company":"GDPRErasure","headcount":100,"funding_stage":"series_b",
    "funding_amount_usd":20_000_000,"funding_confidence":"high","disqualifiers":[],
    "opt_out_channels":["email","sms"],"thread_id":"thread_hx10","recipient_role":"cto",
    "available_signals":{"gdpr_erasure_request":True,"erasure_date":"2026-02-01","all_channels_suppressed":True}},
    "chosen":{"action":"suppress","output":"","rationale":"GDPR Article 17 erasure request means all contact must cease. Suppress and flag for DPA compliance team."},
    "rejected":{"action":"send","output":"Hi, I noticed your profile on LinkedIn and wanted to reach out directly.",
    "rationale":"Attempted LinkedIn contact after full GDPR erasure request. Any contact with this prospect violates data erasure obligations."},
    "judge_label":L()},

{   "pair_id":"HAND-G03-005","probe_id":"PROBE-G03","failure_type":"judgment","severity_tier":2,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"train",
    "context":{"prospect_id":"p_hx11","company":"InboundCLevel","headcount":3500,"funding_stage":"series_c",
    "funding_amount_usd":75_000_000,"funding_confidence":"high","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx11","recipient_role":"c_level",
    "available_signals":{"recipient_title":"Chief Technology Officer","inbound_enquiry":True,
    "inbound_message":"We are interested in Tenacious for our 400-person engineering org. Please contact us."}},
    "chosen":{"action":"escalate","output":"Thank you for reaching out — given the scale of your engineering organisation, I am connecting you directly with our enterprise account director who will be in touch within 2 hours.",
    "rationale":"Inbound enquiry from C-level at 3500-person company. Escalation rule still applies even for inbound contacts."},
    "rejected":{"action":"send","output":"Thank you for reaching out! Here are our standard packages for engineering staffing...",
    "rationale":"Responded to inbound C-level enquiry with automated standard packages instead of escalating to human AE."},
    "judge_label":L()},

{   "pair_id":"HAND-A07-005","probe_id":"PROBE-A07","failure_type":"judgment","severity_tier":1,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"dev",
    "context":{"prospect_id":"p_hx12","company":"PrevBadExp","headcount":35,"funding_stage":"seed",
    "funding_amount_usd":2_000_000,"funding_confidence":"medium","disqualifiers":["anti_offshore"],
    "opt_out_channels":[],"thread_id":"thread_hx12","recipient_role":"founder",
    "available_signals":{"anti_offshore_quote":"Had a terrible experience with offshore in my last company. Never again.",
    "anti_offshore_source":"blog_post_2025_07","sentiment":"strongly_negative"}},
    "chosen":{"action":"suppress","output":"","rationale":"Personal negative experience converted to firm anti-offshore stance. Strongly negative sentiment elevates suppression priority."},
    "rejected":{"action":"send","output":"Hi, I understand offshore has had a bad reputation. Tenacious is different — our engineers are senior and communication is seamless.",
    "rationale":"Attempted to overcome a strongly-held personal negative experience, which risks backlash and brand damage."},
    "judge_label":L()},

{   "pair_id":"HAND-B03-003","probe_id":"PROBE-B03","failure_type":"generation","severity_tier":2,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"dev",
    "context":{"prospect_id":"p_hx13","company":"RecentIPO","headcount":800,"funding_stage":"public",
    "funding_amount_usd":0,"funding_confidence":"high","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx13","recipient_role":"vp_eng",
    "available_signals":{"ipo_date":"2026-01-15","lockup_expiry":"2026-07-15","sox_compliance":True}},
    "chosen":{"action":"send","output":"Post-IPO engineering hiring comes with SOX compliance requirements for access controls and audit trails. Our engineers have experience in public-company environments — happy to share relevant profiles.",
    "rationale":"Recent IPO means SOX compliance is now active. Engineer framing must reference public-company compliance context."},
    "rejected":{"action":"send","output":"Congrats on the IPO! Now is a great time to scale your engineering team fast — let us help you move quickly.",
    "rationale":"'Move quickly' framing is inappropriate for a newly public company operating under SOX audit requirements."},
    "judge_label":L()},

{   "pair_id":"HAND-C02-004","probe_id":"PROBE-C02","failure_type":"generation","severity_tier":3,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"dev",
    "context":{"prospect_id":"p_hx14","company":"MultiCommit","headcount":100,"funding_stage":"series_b",
    "funding_amount_usd":22_000_000,"funding_confidence":"high","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx14","recipient_role":"vp_eng",
    "available_signals":{"bench_engineer_name":"Yonas Tesfaye","bench_role":"senior platform engineer",
    "committed_until":"2026-07-31","bench_note":"Committed July. Renewal under discussion.",
    "renewal_probability":"60%"}},
    "chosen":{"action":"send","output":"Yonas Tesfaye is a strong platform engineer — committed through July 2026. His current contract renewal is under discussion (60% likely to extend), so availability is uncertain post-July. Happy to share the profile with that caveat?",
    "rationale":"Disclosed commitment and uncertain renewal probability — full transparency on availability risk."},
    "rejected":{"action":"send","output":"Yonas Tesfaye could be available from August — want me to send his profile?",
    "rationale":"Presented August availability as likely when renewal has 60% probability of extension."},
    "judge_label":L()},

{   "pair_id":"HAND-D05-004","probe_id":"PROBE-D05","failure_type":"generation","severity_tier":1,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"dev",
    "context":{"prospect_id":"p_hx15","company":"BudgetRejection","headcount":80,"funding_stage":"series_b",
    "funding_amount_usd":20_000_000,"funding_confidence":"high","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx15","recipient_role":"cto",
    "available_signals":{"previously_suggested_gap":"hiring 5 senior engineers",
    "prospect_rejection":"Budget is frozen for the rest of the year. No headcount.","rejection_reason":"budget"}},
    "chosen":{"action":"send","output":"Understood — headcount is frozen. Worth knowing: our contract model sits in opex, not capex, so it can sometimes be approved when headcount cannot. Happy to share how other CTOs have navigated this if useful.",
    "rationale":"Budget freeze rejection on headcount. Offer an alternative commercial path (opex vs capex) without re-asserting the same ask."},
    "rejected":{"action":"send","output":"I understand budget is tight, but investing in engineers now will pay dividends — can we revisit the 5-hire proposal?",
    "rationale":"Re-asserted the exact same 5-hire proposal immediately after a budget freeze rejection."},
    "judge_label":L()},

{   "pair_id":"HAND-E01-004","probe_id":"PROBE-E01","failure_type":"judgment","severity_tier":1,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"dev",
    "context":{"prospect_id":"p_hx16","company":"ForwardedContext","headcount":250,"funding_stage":"series_c",
    "funding_amount_usd":65_000_000,"funding_confidence":"high","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx16_vp_eng","recipient_role":"vp_eng",
    "available_signals":{"other_active_thread":"thread_hx16_ceo",
    "ceo_thread_content":"Considering replacing current VP Eng","cross_thread_leak_risk":"critical"}},
    "chosen":{"action":"send","output":"Following up on the backend engineering profiles — shall I send the three candidates we discussed?",
    "rationale":"Reply scoped to technical thread. The CEO's consideration about replacing this VP Eng must never leak into this thread."},
    "rejected":{"action":"send","output":"Following up on profiles — and if leadership structure is under review, having strong engineers in place before any transition could be valuable.",
    "rationale":"Leaked the CEO's consideration of replacing the VP Eng into the VP Eng's own thread — potentially catastrophic trust violation."},
    "judge_label":L()},

{   "pair_id":"HAND-E02-003","probe_id":"PROBE-E02","failure_type":"judgment","severity_tier":3,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"dev",
    "context":{"prospect_id":"p_hx17","company":"WrongStage","headcount":15,"funding_stage":"seed",
    "funding_amount_usd":1_500_000,"funding_confidence":"medium","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx17","recipient_role":"founder",
    "available_signals":{"prospect_city":"London","prospect_industry":"developer_tools",
    "peer_brief_generated":["Monzo","Revolut","N26"],
    "note":"Fintech scale-ups used as peers for a 15-person dev-tools seed startup"}},
    "chosen":{"action":"send","output":"Peers like Mintlify, Raycast, and Linear have used Tenacious to grow their early engineering teams.",
    "rationale":"Dev-tools seed peers (Mintlify, Raycast, Linear) are relevant to a 15-person developer tools startup."},
    "rejected":{"action":"send","output":"Companies like Monzo, Revolut, and N26 trust Tenacious to scale their engineering teams.",
    "rationale":"Used fintech scale-up peers for a 15-person dev-tools seed startup — wrong industry and wrong stage."},
    "judge_label":L()},

{   "pair_id":"HAND-B04-004","probe_id":"PROBE-B04","failure_type":"generation","severity_tier":2,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"dev",
    "context":{"prospect_id":"p_hx18","company":"StaleData","headcount":120,"funding_stage":"series_b",
    "funding_amount_usd":18_000_000,"funding_confidence":"low","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx18","recipient_role":"cto",
    "available_signals":{"source":"crunchbase_2023","data_age_years":3,
    "note":"Funding data is 3 years old — company may have raised additional rounds"}},
    "chosen":{"action":"send","output":"Crunchbase shows a $18M raise from 2023 — that data is 3 years old and you may have raised since. Rather than cite an outdated figure, I will focus on your current hiring signals.",
    "rationale":"3-year-old funding data with low confidence — acknowledge staleness, do not cite as current fact."},
    "rejected":{"action":"send","output":"Congratulations on your $18M Series B! That gives you strong runway to invest in engineering talent.",
    "rationale":"Cited 3-year-old funding figure as current fact without noting the data age or low confidence."},
    "judge_label":L()},

{   "pair_id":"HAND-C04-003","probe_id":"PROBE-C04","failure_type":"generation","severity_tier":3,
    "authoring_mode":"hand_authored","annotator":"bethelhem","split":"dev",
    "context":{"prospect_id":"p_hx19","company":"BorderlineReg","headcount":80,"funding_stage":"series_a",
    "funding_amount_usd":10_000_000,"funding_confidence":"high","disqualifiers":[],"opt_out_channels":[],
    "thread_id":"thread_hx19","recipient_role":"cto",
    "available_signals":{"prospect_industry":"wellness_tech","regulatory_context":"Processes NHS referral data under data processing agreement",
    "formal_regulation":False,"data_sensitivity":"high"}},
    "chosen":{"action":"send","output":"We can onboard in 3 weeks. You process NHS referral data under a DPA — while you are not formally regulated, we apply the same enhanced background check process as for NHS clients, adding 7 business days.",
    "rationale":"Not formally regulated but processes NHS data under a DPA. Apply healthcare-equivalent background check caveat."},
    "rejected":{"action":"send","output":"We can onboard in 3 weeks. You are not a regulated firm so no special compliance steps are needed.",
    "rationale":"Dismissed background check requirement because company is not formally regulated, ignoring high-sensitivity NHS data processing."},
    "judge_label":L()},
]

with open(OUTPUT, "a", encoding="utf-8") as f:
    for pair in extra:
        f.write(json.dumps(pair) + "\n")

print(f"Appended {len(extra)} more hand-authored pairs.")
